### ISSUE TITLE
Improvement suggestion

### ISSUE THREAD

**Issue by MFlisar** [supervital/SwipeNumberPicker#2]
I love the small and compact look... But the swipe gesture is uncommon for number pickers, so I would suggest following:

A setting that enables increasing/decreasing the number by clicking the left/right end of the view (instead of showing a dialog) + maybe some space for this feature between the left < and the number and the right > and the number. Is that understandable?

What do you think about that?

**Comment by supervital** [comment]
Hello,

Nice idea.
I had the same idea, but, the main issue was a speed/velocity with which a value can be changed.
I'll think about how to easily implement it.

Also, You can fork this.
