### ISSUE TITLE
Intermediate Value Listener

### ISSUE THREAD

**Issue by MFlisar** [supervital/SwipeNumberPicker#3]
Please add the ability to be able to listen to the intermediate values as well...

Some setting like `setEmitIntermediateValuesToListener(boolean emit)` and an extra flag to indicate if a value is an intermediate value in the listener would do it as well...

**Comment by supervital** [comment]
Yes, sounds interesing. It should be fast fix.

**Comment by supervital** [comment]
Thanks, for the idea! I will notify you about the fix!

**Comment by supervital** [comment]
Hi,

I implemented the intermediate mode. Please see the Readme file.


Thanks.
