### ISSUE TITLE
Option - Material Design

### ISSUE THREAD

**Issue by TurKurT656** [supervital/SwipeNumberPicker#4]
Good Lib, but it can be awesome if dialog be Material dialog.

sorry for bad english

**Comment by supervital** [comment]
Hello,

Yeah, I agree. But, it would be overhead.
You can show your custom dialog, like here:
```Java
	swipeNumberPicker.setShowNumberPickerDialog(false);
		swipeNumberPicker.setOnClickListener(new View.OnClickListener() {
			@Override
			public void onClick(View v) {
      
				((SwipeNumberPicker) v).setValue(0, true);
			}
		});
```

**Comment by supervital** [comment]
Hello,

Yeah, I agree. But, it would be overhead for the lib.
You can show your custom dialog, like here:
```Java
	swipeNumberPicker.setShowNumberPickerDialog(false);
	swipeNumberPicker.setOnClickListener(new View.OnClickListener() {
		@Override
		public void onClick(View v) {
          // Create and show your own dialog, and on NumberPicker.OnValueChangeListener
          //call swipeNumberPicker.setValue(newVal, true);                          		
		}
	});
```

Thanks,
Vitalii.

**Comment by TurKurT656** [comment]
TnQ, so Very Nice;

BTW, can we use list of String instead of Numbers in it?

**Comment by TurKurT656** [comment]
it would be nice if we can put List<string> inside it. like spinner.

**Comment by supervital** [comment]
No, strings isn't supported.
For chosen sequence of the numbers you can set min and max numbers.

Please, see the examples.
