### ISSUE TITLE
Nice feature but doesn't work nicely inside a listview/recyclerview

### ISSUE THREAD

**Issue by shahzaibmuneeb** [supervital/SwipeNumberPicker#5]
As the getView() for listview and recyclerview gets called and it resets the picker value.

**Comment by HeinrichReimer** [comment]
Numberpickers inside a list sound like a terrible idea. Can't think of any application that really needs something like that. Yiu should probably use a dialog for that.

**Comment by supervital** [comment]
Hi all.

Actually, from the beginning we use this number in the ListView. It's kindly useful for selecting Quantities for an item with minimum steps for users.

For not resetting Quantities you should store the value in a List or other. It is a typical behavior for the ListView.
Please see this tutorial - http://www.vogella.com/tutorials/AndroidListView/article.html#listviewselection
