### ISSUE TITLE
NumberPicker Dialog doesn't work properly if you enter a custom number

### ISSUE THREAD

**Issue by Alexandersch** [supervital/SwipeNumberPicker#6]
Hi, 

I'm using your library in my project, but I've found a bug. 
Don't know if it's Android or library related.

When I set a custom value in the dialog, as in, I click on the number (in the center) and enter a custom value in the default Android number keyboard that pops up. If I click on OK directly (see screen), it doesn't save the value. It only works if you click on the done button (checkmark icon) in the Android number keyboard first.

![screenshot_20160428-145447](https://cloud.githubusercontent.com/assets/3180083/14886506/6f8d01b6-0d51-11e6-9412-c1a69f0325c4.png)

**Comment by supervital** [comment]
Hello Alexand,


It`s great to hear the widget is used.
Actually, the issue isn`t related to the lib. As I know, it`s known issue for NumberPickers. And you are right. The value saves if you accept it by clicking the Done button.

I will apply the fix.


Thanks!

**Comment by supervital** [comment]
Hi again,


Please, check the fix.


Thanks.

**Comment by supervital** [comment]
Please, update the dependency.

**Comment by Alexandersch** [comment]
Hi, thanks for looking into it!
I'll update te depencency this afternoon. I'll let you know.

**Comment by Alexandersch** [comment]
It works!

**Comment by supervital** [comment]
Great! :)

Thanks for check. :)
